CREATE DATABASE `uzh_minting`

CREATE TABLE `assets` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `attack` INTEGER NOT NULL,
  `speed` INTEGER NOT NULL,
  `defense` INTEGER NOT NULL,
  `health` INTEGER NOT NULL,
  `status` INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

